kind: Deployment
apiVersion: apps/v1
metadata:
  name: caj-fare
  namespace: caj-fare
  labels:
    app: caj-fare
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caj-fare
      version: v1
  template:
    metadata:
      labels:
        app: caj-fare
        version: v1
    spec:
      containers:
        - name: caj-fare
          image: 'image-registry.openshift-image-registry.svc:5000/caj-pipeline/caj-fare'
          ports:
            - containerPort: 8080
              protocol: TCP